const LOG_IN_USER = 'LOG_IN_USER',
  LOG_OUT_USER = 'LOG_OUT_USER',
  LOG_IN_ERROR = 'LOG_IN_ERROR',
  AUTH_USER = 'AUTH_USER',
  AUTH_ERROR = 'AUTH_ERROR';
export { LOG_IN_USER, LOG_OUT_USER, LOG_IN_ERROR, AUTH_USER, AUTH_ERROR };
