const GET_MAIN_INFO = "GET_MAIN_INFO",
      LOADING_MAIN_INFO = "LOADING_MAIN_INFO",
      ERROR_MAIN_INFO = "LOADING_MAIN_INFO",
      SET_MAIN_INFO = "SET_MAIN_INFO";

export {
    GET_MAIN_INFO,
    LOADING_MAIN_INFO,
    ERROR_MAIN_INFO,
    SET_MAIN_INFO,
};