const SET_MARKS = "SET_MARKS",
      GET_MARKS = "GET_MARKS",
      SAVE_MARKS = "SAVE_MARKS",
      CLEAR_MARKS = "CLEAR_MARKS",
      ERROR_MARKS = "ERROR_MARKS",
      SAVE_CENTER_MARK = "SAVE_CENTER_MARK",
      GET_SELECTOR_DATA = "GET_SELECTOR_DATA",
      GET_SPECIAL_MARKS = "GET_SPECIAL_MARKS";

export {
    SET_MARKS,
    GET_MARKS,
    SAVE_MARKS,
    CLEAR_MARKS,
    ERROR_MARKS,
    SAVE_CENTER_MARK,
    GET_SELECTOR_DATA,
    GET_SPECIAL_MARKS,
};